fix: any changes to theme publish a new theme version

diff --git a/.github/workflows/publish-theme.yml b/.github/workflows/publish-theme.yml
--- a/.github/workflows/publish-theme.yml
+++ b/.github/workflows/publish-theme.yml
@@ -6,15 +6,37 @@ on:
             - master
 
 jobs:
-    publish:
-        runs-on: ubuntu-latest
-        outputs:
-            theme_changed: ${{ steps.changed-theme-files.outputs.any_changed }}
+    look_for_change:
+      if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
+      runs-on: ubuntu-latest
+      outputs:
+          theme_changed: ${{ steps.changed-theme-files.outputs.any_changed }}
+      steps:
+          -   uses: actions/checkout@v3
+              with:
+                  fetch-depth: 0
 
+          -   name: Use Node.js 16
+              uses: actions/setup-node@v2-beta
+              with:
+                  node-version: 16
+
+          -   name: Check changes in theme
+              id: changed-theme-files
+              uses: tj-actions/changed-files@v35
+              with:
+                since_last_remote_commit: "true"
+                files: |
+                    apify-docs-theme/**
+
+    publish:
+        needs: look_for_change
+        if: needs.look_for_change.outputs.theme_changed == 'true'
+        runs-on: ubuntu-latest
         steps:
             -   uses: actions/checkout@v3
                 with:
-                    fetch-depth: 0
+                    token: ${{ secrets.GH_TOKEN }}
 
             -   name: Use Node.js 16
                 uses: actions/setup-node@v2-beta
@@ -30,6 +52,11 @@ jobs:
                     echo "access=public" > .npmrc
                     echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" >> .npmrc
 
+            -   name: Bump the theme version
+                run: |
+                    cd $GITHUB_WORKSPACE/apify-docs-theme
+                    npm version patch
+
             -   name: Deploy theme to npm
                 run: |
                     cd $GITHUB_WORKSPACE/apify-docs-theme
@@ -38,17 +65,36 @@ jobs:
                     NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
                     GIT_USER: "barjin:${{ secrets.GH_TOKEN }}"
                     GH_TOKEN: ${{ secrets.GH_TOKEN }}
-            
-            - name: Get changed files in the docs folder
-              id: changed-theme-files
-              uses: tj-actions/changed-files@v35
+
+            - name: Wait until the new theme version is available on npm
+              run: |
+                cd $GITHUB_WORKSPACE/apify-docs-theme
+                PACKAGE_JSON=$(npm view --json); 
+                PACKAGE_NAME=$(jq -r .name <(echo $PACKAGE_JSON));
+                PACKAGE_VER=$(jq -r .version <(echo $PACKAGE_JSON));
+                for i in $(seq 1 10); do
+                    npm show $PACKAGE_NAME@$PACKAGE_VER &> /dev/null;
+                    if [[ $? -ne 0 ]]; then
+                        echo "The new package version ($PACKAGE_VER) is not yet available, waiting 30 seconds...";
+                        sleep 30;
+                        continue;
+                    fi;
+                    echo "The new package version ($PACKAGE_VER) is live, proceeding!";
+                    break;
+                done;
+                npm show $PACKAGE_NAME@$PACKAGE_VER # fails if the package is not available, succeeds if it is
+
+            - name: Commit the new theme version
+              uses: stefanzweifel/git-auto-commit-action@v4
               with:
-                files: |
-                    apify-docs-theme/**
+                commit_message: '[skip ci] Automatic theme publishing workflow'
+
+                commit_user_name: Apify Bot
+                commit_user_email: my-github-actions-bot@example.org
+                commit_author: Apify Bot <apify@apify.com>
     
     rebuild-docs:
         needs: publish
-        if: needs.publish.outputs.theme_changed == 'true'
         strategy:
             matrix:
                 include:
